version: 2
updates:
  # Check package.json for updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

  # Check Dockerfile for updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
