name: CI/CD pipeline
on: push

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  docker_build:
    name: Build and Push Docker image
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Extract branch name
        shell: bash
        run: REF=${GITHUB_REF#refs/heads/} && arrREF=(${REF//// }) && echo "##[set-output name=branch;]$(echo ${arrREF[-1]})"
        id: extract_branch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Login to ECR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: npm run test

  UI_tests:
    name: UI tests
    runs-on: ubuntu-latest
    needs: install_dependencies
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    env:
      WEBAPP_CLIENT_SECRET: ${{ secrets.WEBAPP_CLIENT_SECRET }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Copy env vars
        run: cp .env.example .env.local
      - name: Run Cypress UI tests
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/**/*.spec.ts
          browser: chrome
          start: npm run start
          build: npm run build
          wait-on: "http://localhost:3000"
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

  end_to_end_tests:
    name: End to end tests
    runs-on: ubuntu-latest
    needs: install_dependencies

    env:
      WEBAPP_CLIENT_SECRET: ${{ secrets.WEBAPP_CLIENT_SECRET }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}
      GOV_NOTIFY_FEEDBACK_EMAIL_ADDRESS: ${{ secrets.GOV_NOTIFY_FEEDBACK_EMAIL_ADDRESS }}

    outputs:
      service_commit_hash: ${{ steps.get_service_commit_hash.outputs.service_commit_hash }}

    steps:
      - name: Checkout Service repo
        uses: actions/checkout@v2.3.4
        with:
          repository: "mcagov/beacons-service"
      - id: get_service_commit_hash
        name: Get commit hash from Service repo
        run: echo "::set-output name=service_commit_hash::$(git rev-parse HEAD)"
      - name: Checkout webapp repo
        uses: actions/checkout@v2.3.4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Bring up API and DB
        run: |
          SERVICE_COMMIT_HASH=${{ steps.get_service_commit_hash.outputs.service_commit_hash }} docker compose -f docker-compose.e2e.yml up --detach
      - name: Copy env vars
        run: cp .env.example .env.local
      - name: Checkout node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - name: Run Cypress end to end tests
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/endToEnd/*
          browser: chrome
          start: npm run start
          build: npm run build
          wait-on: "http://localhost:8080/spring-api/actuator/health"
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
      - name: Stop containers
        if: always()
        run: docker-compose --file "docker-compose.e2e.yml" down

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run linter
        run: npm run lint

  prettier_check:
    name: Prettier check
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run prettier
        run: npm run format:check

  docker_lint:
    name: Docker lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Docker lint
        uses: brpaz/hadolint-action@v1.5.0

  codeql_check:
    name: CodeQL check
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  deploy_dev:
    if: github.ref == 'refs/heads/main'
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    needs:
      [
        install_dependencies,
        docker_build,
        unit_tests,
        UI_tests,
        end_to_end_tests,
        lint_check,
        prettier_check,
        docker_lint,
        codeql_check,
      ]

    steps:
      - name: Trigger Integration Pipeline
        run: |
          curl -X POST  -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.MCA_GITHUB_TOKEN }}" \
            https://api.github.com/repos/mcagov/beacons-integration/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main", "inputs": {"updateImageTags": "true"}}'
